server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url : "jdbc:mysql://localhost:3306/shopapp"
    username : root
    password : root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
#  expiration: 2592000
#    #30 days = 30 * 24 * 60 * 60
#  secretKey: Minh Nghia
  signerKey: "z+7kjfwfgxuzW2+1/EVCduqLWkVwR/atuCqg+EtTogGK5RdioGkeSeY3Mfyps89G"
  valid-duration: 3600
  refreshable-duration: 36000
